# Generated by Django 3.1.3 on 2020-11-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='updated_text',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='status',
            field=models.IntegerField(choices=[('INITIATED_CREATE', 1), ('APPROVED', 2), ('DELETED', 3), ('INITIATED_DELETE', 4), ('INITIATED_UPDATE', 5)], default=2),
        ),
    ]
