# Generated by Django 3.1.3 on 2020-11-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='actionlogmodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
