# Generated by Django 3.1.3 on 2020-11-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201129_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogmodel',
            name='action',
            field=models.IntegerField(choices=[('TWEET', 1), ('LOGIN', 2), ('DELETE', 3), ('REQUESTED_CHANGE', 4), ('APPROVED', 5), ('GET_TWEETS', 6)], default=1),
        ),
    ]
