# Generated by Django 3.1.3 on 2020-11-29 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201129_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlogmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
