# Generated by Django 3.1.3 on 2020-11-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20201129_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogmodel',
            name='action',
            field=models.IntegerField(choices=[('TWEET', 1), ('LOGIN', 2), ('DELETE', 3), ('REQUESTED_CHANGE', 4), ('APPROVED', 5), ('GET_TWEETS', 6), ('SIGN_UP', 7)], default=1),
        ),
        migrations.AlterField(
            model_name='actionlogmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
