# Generated by Django 3.1.3 on 2020-11-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201130_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogmodel',
            name='action',
            field=models.IntegerField(choices=[('TWEET', 1), ('LOGIN', 2), ('DELETE', 3), ('REQUESTED_CHANGE', 4), ('APPROVED', 5), ('GET_TWEETS', 6), ('SIGN_UP', 7), ('READ_LOGS', 8)], default=1),
        ),
    ]
